### ISSUE TITLE
It downloads same wallpaper all the time

### ISSUE THREAD

**Issue by Morteza-Rastgoo** [auino/500px-osx-background#3]

**Comment by ctissier** [comment]
As far as I understood, it doesn't download the same wallpaper all the time (we can see that the /private/tmp/500px_img.png image changes each time the script is executed).

However, I think Mac OS (High Sierra at least) uses a cache and doesn't refresh the background image if the filepath doesn't change (at least until the next reboot).

Adding a changing string in the filename (a timestamp for example) resolves the issue. However, we need then to delete the previous image in order not to fill up the /tmp folder.

**Comment by ctissier** [comment]
I've made the changes to the code. Can I do a PR ?

`RANDOMIZER=$(date +%s)`
...
```
# deleting previous imgs
rm $DIR/500px_img*

# getting image data from url
curl -s "$IMG" -o $DIR/500px_img_$RANDOMIZER.png
```
...
`osascript -e 'tell application "System Events" to set picture of every desktop to ("'$DIR'/500px_img_'$RANDOMIZER'.png" as POSIX file as alias)'`

**Comment by auino** [comment]
Of course, thank you for your message and support.
If you wish, I can also add you as a developer of the tool.

**Comment by ctissier** [comment]
I did the PR.

Sure, I'll be happy to be added as a developer of the script :)
